create database customer_behaviour;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(`purchase_amount_(usd)`) AS revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id,`purchase_amount_(usd)`
FROM customer WHERE discount_applied = 'YES'
AND `purchase_amount_(usd)` >= (SELECT AVG(`purchase_amount_(usd)`)FROM customer);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND (AVG(review_rating),2)AS "AVG. PRODUCT RATING" FROM customer
GROUP BY item_purchased ORDER BY AVG(review_rating) DESC LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND (AVG(`purchase_amount_(usd)`),2)AS "Average Purchase Amount" FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND (AVG(`purchase_amount_(usd)`),2) AS "Average_Spend",
ROUND(SUM(`purchase_amount_(usd)`),2) AS "total_revenue" FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,Average_Spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied= 'YES' THEN 1 ELSE 0 END)/COUNT(*),2) AS DISCOUNT_PURCHASE FROM customer
GROUP BY item_purchased
ORDER BY DISCOUNT_PURCHASE DESC LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
--number of previous purchases, and show the count of each segment. 

with customer_type as ( select previous_purchases,customer_id,
case 
WHEN previous_purchases = 1 THEN "New" 
WHEN previous_purchases BETWEEN 2 AND 10 THEN " Returning" 
ELSE " Loyal" END as customer_segment from customer)
select customer_segment, count(*) AS "Number of Customers" from customer_type
group by customer_segment



--Q8  What are the top 3 most purchased products within each category? 
WITH avg_frequency AS (
    SELECT
        category,
        item_purchased,
        AVG(purchase_frequency_days) AS avg_purchase_frequency
    FROM customer
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        item_purchased,
        category,
        avg_purchase_frequency,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY avg_purchase_frequency DESC
        ) AS item_rank
    FROM avg_frequency
)
SELECT *
FROM ranked_items
WHERE item_rank <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS "repeat buyers" from customer
where previous_purchases >=5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 
select age_group, SUM(`purchase_amount_(usd)`) AS Total_revenue from customer
GROUP BY age_group 
order by Total_revenue desc

